//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesisUdistrital
{
    using System;
    using System.Collections.Generic;
    
    public partial class persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public persona()
        {
            this.procesoDocumentacion = new HashSet<procesoDocumentacion>();
            this.procesoDocumentacion1 = new HashSet<procesoDocumentacion>();
            this.soporteXRadicado = new HashSet<soporteXRadicado>();
        }
    
        public long idPersona { get; set; }
        public System.Guid idPersonaUnique { get; set; }
        public string primerNombre { get; set; }
        public string segundoNombre { get; set; }
        public string primerApellido { get; set; }
        public string segundoApellido { get; set; }
        public long tipoDocumento { get; set; }
        public string noDocumento { get; set; }
        public System.DateTime fechaNacimiento { get; set; }
        public long genero { get; set; }
        public Nullable<bool> personaModificada { get; set; }
    
        public virtual genero genero1 { get; set; }
        public virtual tipoDocumento tipoDocumento1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<procesoDocumentacion> procesoDocumentacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<procesoDocumentacion> procesoDocumentacion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<soporteXRadicado> soporteXRadicado { get; set; }
    }
}
