//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesisUdistrital
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DocumentacionDemoEntities : DbContext
    {
        public DocumentacionDemoEntities()
            : base("name=DocumentacionDemoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dane> dane { get; set; }
        public virtual DbSet<genero> genero { get; set; }
        public virtual DbSet<hechoVictimizante> hechoVictimizante { get; set; }
        public virtual DbSet<parentesco> parentesco { get; set; }
        public virtual DbSet<persona> persona { get; set; }
        public virtual DbSet<soporte> soporte { get; set; }
        public virtual DbSet<soporteXRadicado> soporteXRadicado { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tipoDocumento> tipoDocumento { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<procesoDocumentacion> procesoDocumentacion { get; set; }
        public virtual DbSet<vw_consultaCasoDocumentacion> vw_consultaCasoDocumentacion { get; set; }
        public virtual DbSet<vw_informacionPersona> vw_informacionPersona { get; set; }
    }
}
