//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesisUdistrital
{
    using System;
    using System.Collections.Generic;
    
    public partial class soporteXRadicado
    {
        public long idSoportePersona { get; set; }
        public long idSoporte { get; set; }
        public long idPersona { get; set; }
        public string rad { get; set; }
        public bool estadoSoporte { get; set; }
        public string rutaSoporte { get; set; }
        public long usuarioCreacionSoporte { get; set; }
        public System.DateTime fechaCreacionSoporte { get; set; }
    
        public virtual soporte soporte { get; set; }
        public virtual persona persona { get; set; }
    }
}
