//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesisUdistrital
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarioXradicado
    {
        public long idAsignacion { get; set; }
        public string rad { get; set; }
        public string proceso { get; set; }
        public bool estado { get; set; }
        public long idusuario { get; set; }
        public System.DateTime fechaAsignacion { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
