//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesisUdistrital
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_consultaCasoDocumentacion
    {
        public long id { get; set; }
        public System.Guid uniqueIdentifier { get; set; }
        public string rad { get; set; }
        public string proceso { get; set; }
        public long idPersonaVictima { get; set; }
        public System.Guid idPersonaUniqueVictima { get; set; }
        public string primerNombreVictima { get; set; }
        public string segundoNombreVictima { get; set; }
        public string primerApellidoVictima { get; set; }
        public string segundoApellidoVictima { get; set; }
        public string tipoDocumentoVictima { get; set; }
        public string noDocumentoVictima { get; set; }
        public System.DateTime fechaNacimientoVictima { get; set; }
        public string GeneroVictima { get; set; }
        public string nombreHechoVictimizante { get; set; }
        public string nombreDeptoOcurrenciaHecho { get; set; }
        public long codigoDeptoOcurrenciaHecho { get; set; }
        public string nombreMuniOcurrenciaHecho { get; set; }
        public long codigoMuniOcurrenciaHecho { get; set; }
        public System.DateTime fechaOcurrenciaHecho { get; set; }
        public long idPersonaDestinatario { get; set; }
        public System.Guid idPersonaUniqueDestinatario { get; set; }
        public string primerNombreDestinatario { get; set; }
        public string segundoNombreDestinatario { get; set; }
        public string primerApellidoDestinatario { get; set; }
        public string segundoApellidoDestinatario { get; set; }
        public string tipoDocumentoDestinatario { get; set; }
        public string noDocumentoDestinatario { get; set; }
        public System.DateTime fechaNacimientoDestinatario { get; set; }
        public string GeneroDestinatario { get; set; }
        public double porcentaje { get; set; }
    }
}
