//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesisUdistrital
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_informacionPersona
    {
        public long idPersona { get; set; }
        public System.Guid idPersonaUnique { get; set; }
        public string primerNombre { get; set; }
        public string segundoNombre { get; set; }
        public string primerApellido { get; set; }
        public string segundoApellido { get; set; }
        public string tipoDocumento { get; set; }
        public string noDocumento { get; set; }
        public System.DateTime fechaNacimiento { get; set; }
        public string Genero { get; set; }
    }
}
